---
jenkins_repo_url: deb https://pkg.jenkins.io/debian-stable binary/
jenkins_repo_key_url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
jenkins_version: "{{ ansible_env.JENKINS_VERSION }}"
jenkins_home: /var/lib/jenkins
efs_filesystem_dns: "{{ ansible_env.EFS_FILESYSTEM_DNS }}"
jenkins_admin_username: admin
jenkins_admin_password: admin
jenkins_process_user: jenkins
jenkins_process_group: jenkins
jenkins_plugins: workflow-aggregator golang credentials-binding git timestamper ws-cleanup junit blueocean sonar pipeline-aws http_request
sonar_server_url: http://localhost:9000/
sonar_runner_version: 3.0.3.778
