---
jenkins_repo_url: deb https://pkg.jenkins.io/debian-stable binary/
jenkins_repo_key_url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
jenkins_version: "{{ ansible_env.JENKINS_VERSION }}"
jenkins_home: /var/lib/jenkins
jenkins_process_user: jenkins
jenkins_process_group: jenkins

efs_filesystem_dns: "{{ ansible_env.EFS_FILESYSTEM_DNS }}"

jenkins_admin_username: "{{ ansible_env.JENKINS_ADMIN_USERNAME }}"
jenkins_admin_password: "{{ ansible_env.JENKINS_ADMIN_PASSWORD }}"
jenkins_plugins: "{{ ansible_env.JENKINS_PLUGINS }}"

golang_version: "{{ ansible_env.GOLANG_VERSION }}"

sonarqube_server_url: "{{ ansible_env.SONARQUBE_SERVER_URL }}"
sonar_scanner_version: "{{ ansible_env.SONAR_SCANNER_VERSION }}"

caddy_pipeline_job: "{{ ansible_env.CADDY_PIPELINE_JOB }}"
caddy_pipeline_repo: "{{ ansible_env.CADDY_PIPELINE_REPO }}"
caddy_pipeline_file: "{{ ansible_env.CADDY_PIPELINE_FILE }}"

msg_provider_auth_id: "{{ ansible_env.MSG_PROVIDER_AUTH_ID }}"
msg_provider_auth_token: "{{ ansible_env.MSG_PROVIDER_AUTH_TOKEN }}"
msg_provider_src_phone: "{{ ansible_env.MSG_PROVIDER_SRC_PHONE }}"
msg_provider_dest_phone: "{{ ansible_env.MSG_PROVIDER_DEST_PHONE }}"

statuspage_api_key: "{{ ansible_env.STATUSPAGE_API_KEY }}"

shared_library: https://github.com/bimlendu/pipeline-shared-libs.git