---
nginx_repo_key_url: http://nginx.org/keys/nginx_signing.key
nginx_repo_url: deb http://nginx.org/packages/ubuntu/ xenial nginx
jenkins_repo_url: deb https://pkg.jenkins.io/debian-stable binary/
jenkins_repo_key_url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
jenkins_version: "{{ ansible_env.JENKINS_VERSION }}"
jenkins_home: /var/lib/jenkins
efs_filesystem_dns: "{{ ansible_env.EFS_FILESYSTEM_DNS }}"
jenkins_admin_username: admin
jenkins_admin_password: admin
jenkins_process_user: jenkins
jenkins_process_group: jenkins