---
- name: Install required packages.
  apt:
    name:
      - unzip
    state: installed

- name: Download and unzip sonarqube.
  unarchive:
    src: "{{ sonarqube_download_url }}"
    dest: /opt/
    remote_src: True