---
- name: Install required packages.
  apt:
    name:
      - unzip
    state: installed

- name: Download and unzip sonarqube.
  unarchive:
    src: "{{ sonarqube_download_url }}"
    dest: /opt/
    remote_src: True

- name: Check sonar installation
  stat: path={{ sonarqube_install_dir }}
  register: sonar_exists

- name: Move sonarqube to {{ sonarqube_install_dir }}
  command: mv /opt/sonarqube-{{ sonarqube_version }} {{ sonarqube_install_dir }}
  when: not sonar_exists.stat.exists

- name: Configure sonar jdbc properties.
  template:
    src: sonar.properties
    dest: "{{ sonarqube_install_dir }}/conf/sonar.properties"

- name: Download sonar-golang plugin
  get_url:
    url: "{{ sonarqube_golang_plugin_url }}"
    dest: "{{ sonarqube_install_dir }}/extensions/plugins/"
    mode: 0644

- name: Add sonarqube systemd unit.
  template:
    src: sonar.service
    dest: /etc/systemd/system/sonar.service

- name: Enable/Start Sonarqube
  systemd: state=started name=sonar.service daemon_reload=yes enabled=yes