---
- name: Setup Jenkins/SonarQube
  hosts: localhost
  user: root
  connection: local

  tasks:
    - shell: exit 1
      register: task_result
      until: task_result.rc == 0
      retries: 10
      delay: 1
      ignore_errors: yes

  roles:
    - jenkins
    - sonarqube
