---
hugo_version: "0.25.1"
hugo_download_url: https://github.com/gohugoio/hugo/releases/download/v{{ hugo_version }}/hugo_{{ hugo_version }}_Linux-64bit.deb
caddy_version: "0.10.4"
caddy_download_url: https://github.com/mholt/caddy/releases/download/v{{ caddy_version }}/caddy_v{{ caddy_version }}_linux_amd64.tar.gz
caddy_binary: /usr/local/bin/caddy
caddy_user: www-data
caddy_group: www-data