---
- name: Install hugo.
  apt:
    deb: "{{ hugo_download_url }}"

- name: Download and extract caddy.
  unarchive:
    src: "{{ initial_caddy_version }}"
    dest: /usr/local/bin/
    remote_src: True
    mode: 0755
    owner: root
    group: root
  notify:
    - restart caddy

- name: Add group for caddy.
  group:
    name: "{{ caddy_group }}"
    system: true
    state: present

- name: Add user for caddy.
  user:
    name: "{{ caddy_user }}"
    group: "{{ caddy_group }}"
    system: true
    shell: /usr/sbin/nologin
    home: /var/www

- name: Create caddy confing directory.
  file:
    path: /etc/caddy
    owner: root
    group: "{{ caddy_group }}"
    state: directory

- name: Create caddy data directory.
  file:
    path: /etc/ssl/caddy
    owner: "{{ caddy_user }}"
    group: root
    state: directory
    mode: 0770

- name: Create caddy homedir.
  file:
    path: /var/www
    owner: "{{ caddy_user }}"
    group: "{{ caddy_group }}"
    mode: 0555
    state: directory

- name: Create caddyfile
  copy:
    src: "{{ role_path }}/files/Caddyfile"
    dest: /etc/caddy/Caddyfile
    owner: "{{ caddy_user }}"
    group: "{{ caddy_group }}"
    mode: 0444
  notify:
    - restart caddy

- name: Create caddy systemd unit
  copy:
    src: "{{ role_path }}/files/caddy.service"
    dest: /etc/systemd/system/caddy.service
    mode: 0644
  notify:
    - restart caddy

- name: Enable/Start caddy-server
  systemd: state=started name=caddy.service daemon_reload=yes enabled=yes
