---
- name: Install nfs/efs client packages.
  apt:
    name:
      - nfs-common
    state: installed

- name: Mount EFS filesystem.
  mount:
    path: "{{ jenkins_home }}"
    src: "{{ efs_filesystem_dns }}:/" 
    fstype: nfs4
    opts: nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,_netdev
    state: mounted

- name: Add Jenkins apt repository key.
  apt_key:
    url: "{{ jenkins_repo_key_url }}"
    state: present

- name: Add Jenkins apt repository.
  apt_repository:
    repo: "{{ jenkins_repo_url }}"
    state: present
    update_cache: yes

- name: Prevent jenkins from starting up on install.
  copy:
    src: "{{ role_path }}/files/policy-rc.d"
    dest: /usr/sbin/policy-rc.d

- name: Install packages.
  apt:
    name:
      - jenkins={{ jenkins_version }}
    state: installed

- name: Create custom init scripts directory.
  file:
    path: "{{ jenkins_home }}/init.groovy.d"
    state: directory
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0775

- name: Add users script.
  template:
    src: basic-security.groovy
    dest: "{{ jenkins_home }}/init.groovy.d/basic-security.groovy"
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0775

- name: Add plugins install script.
  template:
    src: install-plugins.groovy
    dest: "{{ jenkins_home }}/init.groovy.d/install-plugins.groovy"
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0775

- name: Bypass - jenkins.install.InstallUtil.lastExecVersion
  copy:
    src: "{{ jenkins_version }}"
    dest: "{{ jenkins_home }}/jenkins.install.InstallUtil.lastExecVersion"
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    remote_src: True

- name: Ensure Jenkins is started and runs on startup.
  service: name=jenkins state=started enabled=yes

- name: Remove policy-rc.d.
  file:
    path: /usr/sbin/policy-rc.d
    state: absent